// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import { initFormatters } from './formatters';
import { loadedFormatters, loadedLocales, locales } from './i18n-util';
import af from './af';
import ar from './ar';
import ca from './ca';
import cs from './cs';
import da from './da';
import de from './de';
import el from './el';
import en from './en';
import es from './es';
import fr from './fr';
import hr from './hr';
import hu from './hu';
import hy from './hy';
import it from './it';
import ja from './ja';
import lg from './lg';
import ms from './ms';
import nl from './nl';
import pt from './pt';
import qu from './qu';
import ro from './ro';
import sk from './sk';
import sr from './sr';
import sw from './sw';
import th from './th';
import tr from './tr';
import vi from './vi';
var localeTranslations = {
    af: af,
    ar: ar,
    ca: ca,
    cs: cs,
    da: da,
    de: de,
    el: el,
    en: en,
    es: es,
    fr: fr,
    hr: hr,
    hu: hu,
    hy: hy,
    it: it,
    ja: ja,
    lg: lg,
    ms: ms,
    nl: nl,
    pt: pt,
    qu: qu,
    ro: ro,
    sk: sk,
    sr: sr,
    sw: sw,
    th: th,
    tr: tr,
    vi: vi,
};
export var loadLocale = function (locale) {
    if (loadedLocales[locale])
        return;
    loadedLocales[locale] = localeTranslations[locale];
    loadFormatters(locale);
};
export var loadAllLocales = function () { return locales.forEach(loadLocale); };
export var loadFormatters = function (locale) {
    return void (loadedFormatters[locale] = initFormatters(locale));
};
//# sourceMappingURL=i18n-util.sync.js.map