// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import { useContext } from 'react';
import { initI18nReact } from 'typesafe-i18n/react';
import { loadedFormatters, loadedLocales } from './i18n-util';
var _a = initI18nReact(loadedLocales, loadedFormatters), TypesafeI18n = _a.component, I18nContext = _a.context;
var useI18nContext = function () { return useContext(I18nContext); };
export { I18nContext, useI18nContext };
export default TypesafeI18n;
//# sourceMappingURL=i18n-react.js.map