import React from "react"
import { getStorybookUI } from "@storybook/react-native"

// Set global flag to detect Storybook environment in theme
;(global as typeof globalThis & { STORYBOOK_ENABLED?: boolean }).STORYBOOK_ENABLED = true

import { NavigationContainer } from "@react-navigation/native"
import { ThemeProvider } from "@rn-vui/themed"
import { createNativeStackNavigator } from "@react-navigation/native-stack"
import theme from "@app/rne-theme/theme"
import TypesafeI18n from "@app/i18n/i18n-react"

// import './doctools'

// storybook.requires.js auto generated by storybook
// eslint-disable-next-line import/no-unresolved
import "./storybook.requires"
import { detectDefaultLocale } from "../app/utils/locale-detector"
import RNBootSplash from "react-native-bootsplash"
import { GestureHandlerRootView } from "react-native-gesture-handler"
import { NotificationsProvider } from "../app/components/notifications"

RNBootSplash.hide({ fade: true })

const StorybookUI = getStorybookUI({
  enableWebsockets: true,
  onDeviceUI: true,
  initialSelection: { kind: "ChatBot Screen", name: "Default" },
  shouldPersistSelection: false,
})

const Stack = createNativeStackNavigator()

const ThemeWrapper: React.FC<React.PropsWithChildren> = ({ children }) => (
  <ThemeProvider theme={theme}>{children}</ThemeProvider>
)

const I18nWrapper: React.FC<React.PropsWithChildren> = ({ children }) => (
  <TypesafeI18n locale={detectDefaultLocale()}>{children}</TypesafeI18n>
)

export const StorybookUIRoot: React.FC = () => (
  <GestureHandlerRootView style={{ flex: 1 }}>
    <I18nWrapper>
      <ThemeWrapper>
        <NotificationsProvider>
          <NavigationContainer>
            <Stack.Navigator>
              <Stack.Screen
                name="Home"
                options={{
                  headerShown: false,
                  animation: "none",
                }}
                component={StorybookUI}
              />
            </Stack.Navigator>
          </NavigationContainer>
        </NotificationsProvider>
      </ThemeWrapper>
    </I18nWrapper>
  </GestureHandlerRootView>
)
