#@data/values
---
git_uri: git@github.com:blinkbitcoin/blink-mobile.git
concourse_locks_git_uri: git@github.com:blinkbitcoin/concourse-locks.git

git_mobile_deployments_uri: git@github.com:blinkbitcoin/blink-mobile-deployments.git
git_version_branch: main

git_branch: main
pipeline_git_branch: main
git_build_number_branch: build-numbers

github_private_key: ((github-blinkbitcoin.private_key))
github_api_token: ((github-blinkbitcoin.api_token))

docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))

gh_org: blinkbitcoin
gh_repository: blink-mobile

build_artifacts_bucket_name: galoy-build-artifacts
build_artifacts_bucket_creds: ((build-artifacts-bucket-creds.creds_json))

artifacts_bucket_name: ((staging-gcp-creds.bucket_name))
staging_inception_creds: ((staging-gcp-creds.creds_json))

browserstack_user: ((browserstack-creds.browserstack_user))
browserstack_access_key: ((browserstack-creds.browserstack_access_key))
browserstack_ios_build: ((browserstack-creds.browserstack_ios_build))
browserstack_android_build: ((browserstack-creds.browserstack_android_build))
galoy_test_tokens: ((galoy-tokens.galoy_test_tokens))
galoy_token_2: ((galoy-tokens.galoy_token_2))
mailslurp_api_key: ((galoy-tokens.mailslurp_api_key))

android_keystore: ((android.keystore))
fastlane_match_password: ((fastlane.match_password))
fastlane_match_keychain_password: ((fastlane.match_keychain_password))
appstore_api_key: ((appstore.appstore_api_key))
appstore_api_key_id: ((appstore.appstore_api_key_id))
appstore_issuer_id: ((appstore.appstore_api_issuer_id))
