name: E2E

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e-android:
    name: Android
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GRADLE_USER_HOME: /nix/gradle
      GRADLE_OPTS: >-
        -Dorg.gradle.internal.http.socketTimeout=120000
        -Dorg.gradle.internal.http.connectionTimeout=120000
        -Dorg.gradle.workers.max=2

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          build-mount-path: /nix
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Prepare /nix for Nix installer
        shell: bash
        run: |
          sudo mkdir -p /nix
          sudo chown root:root /nix
          sudo chmod 0755 /nix
          echo "Ownership after fix:"
          ls -ld /nix

      - uses: actions/checkout@v4

      # Install Nix + enable cache
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          use-flakehub: false

      # Caching
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            ios/Pods
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock', '**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Move Docker data-root to /nix/docker
        run: |
          sudo systemctl stop docker
          sudo mkdir -p /nix/docker
          echo '{"data-root":"/nix/docker"}' | sudo tee /etc/docker/daemon.json
          sudo rsync -aH --delete /var/lib/docker/ /nix/docker/ || true
          sudo systemctl start docker
          docker info

      - name: Relocate caches to /nix
        run: |
          sudo mkdir -p /nix/{tmp,yarn-cache,npm-cache,gradle,avd}
          sudo chown -R $USER:$USER /nix/{tmp,yarn-cache,npm-cache,gradle,avd}
          {
            echo "TMPDIR=/nix/tmp"
            echo "YARN_CACHE_FOLDER=/nix/yarn-cache"
            echo "NPM_CONFIG_CACHE=/nix/npm-cache"
            echo "GRADLE_USER_HOME=/nix/gradle"
            echo "ANDROID_AVD_HOME=/nix/avd"
            echo "ANDROID_PREFS_ROOT=/nix/avd"
          } >> $GITHUB_ENV

      # Installations
      - name: Install Node Modules and Pods
        run: nix develop -c yarn install
        env:
          LANG: en_US.UTF-8

      # Metro
      - name: Start Metro
        run: |
          nix develop -c sh -c 'yarn start' &
          echo "METRO_PID=$!" >> $GITHUB_ENV

      # Start Tilt
      - name: Tilt CI
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_wait_seconds: 45
          command: nix develop -c sh -c 'cd dev && tilt ci'
      - name: Tilt Server
        run: |
          lsof -ti:10350 | xargs kill -9 || true
          nix develop -c sh -c 'cd dev && tilt up' &
          echo "TILT_SERVER_PID=$!" >> $GITHUB_ENV

      # Builds
      - name: Android build
        timeout-minutes: 30
        run: |
          cat >> android/gradle.properties <<'EOF'
          org.gradle.console=plain
          org.gradle.logging.level=warn
          org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
          org.gradle.caching=true
          org.gradle.parallel=true
          org.gradle.daemon=false
          EOF

          # Keep the step alive
          ( while sleep 60; do echo "[build] running..."; done ) & HB=$!

          set +e
          timeout 30m nix develop -c yarn e2e:build android.emu.debug
          CODE=$?

          # If it failed or hung out, cleanup locks and retry with safer settings
          if [ $CODE -ne 0 ]; then
            pkill -f GradleDaemon || true
            rm -rf "$GRADLE_USER_HOME"/caches/*/file-locks || true
            sed -i 's/^org\.gradle\.parallel=true/org.gradle.parallel=false/' android/gradle.properties || true
            timeout 20m nix develop -c yarn e2e:build android.emu.debug
            CODE=$?
          fi

          kill $HB || true
          exit $CODE

      # Tests on Android Emulator
      - name: Start Android Emulator
        run: |
          nix develop -c sh -c 'emulator -avd Pixel_API_34 -gpu swiftshader -wipe-data -no-boot-anim' &
          nix develop -c adb wait-for-device
          nix develop -c sh -c 'adb shell screenrecord --bit-rate 4000000 --time-limit 99999999 /sdcard/screenRecord.mp4' &
          echo "EMU_RECORD=$!" >> $GITHUB_ENV

      - name: Run Detox Tests on Android Emulator
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_wait_seconds: 1
          max_attempts: 3
          command: |
            rm -rf android-recordings || true
            nix develop -c tilt trigger dev-setup
            nix develop -c tilt wait --timeout 5m --for=condition=Ready uiresources dev-setup
            nix develop -c yarn e2e:test android.emu.debug -d --take-screenshots all --record-videos all --record-logs all --artifacts-location android-recordings

      - name: Kill Android Emulator
        if: always()
        continue-on-error: true
        run: |
          kill -SIGINT $EMU_RECORD
          nix develop -c adb pull /sdcard/screenRecord.mp4 ./screenRecordUnopt.mp4
          ffmpeg -i screenRecordUnopt.mp4 screenRecord.mp4
          nix develop -c adb emu kill

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-recordings
          path: android-recordings

      # Upload recordings to GCS bucket
      - uses: "google-github-actions/auth@v2"
        if: always()
        with:
          credentials_json: "${{ secrets.BUILD_ARTIFACTS_BUCKET_KEY }}"
      - uses: "google-github-actions/upload-cloud-storage@v2"
        if: always()
        with:
          path: screenRecord.mp4
          gzip: false
          predefinedAcl: publicRead
          headers: |-
            content-type: video/mp4
          destination: galoy-mobile-recordings/android-recordings/${{ github.run_id }}
      - name: Append Direct Links to GitHub Actions Summary
        if: always()
        run: |
          echo "## Android Recording" > $GITHUB_STEP_SUMMARY

          COMPLETE_RECORDING_URL="https://storage.googleapis.com/galoy-mobile-recordings/android-recordings/${{ github.run_id }}/screenRecord.mp4"
          echo "Full Recording: [Click here](<$COMPLETE_RECORDING_URL>)" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Test Suite:" >> $GITHUB_STEP_SUMMARY

          find android-recordings -type f -name "*.mp4" | while read file; do
            RELATIVE_PATH="${file#android-recordings/}"
            FILE_URL="${BASE_URL}/${RELATIVE_PATH}"
            TEST_NAME=$(echo "$RELATIVE_PATH" | sed -E 's|.*/(.*)/test\.mp4|\1|')

            echo "- $TEST_NAME" >> $GITHUB_STEP_SUMMARY
          done

      - name: Disk usage (report)
        if: always()
        shell: bash
        run: |
          set -u
          echo "== root =="
          df -h /
          echo "== /mnt =="
          df -h /mnt
          echo "== workspace =="
          df -h "$GITHUB_WORKSPACE"
          if [ -d /nix ]; then
            echo "== /nix =="
            df -h /nix
          fi

      # Cleanup
      - name: Terminate Metro
        if: always()
        continue-on-error: true
        run: kill $METRO_PID

      - name: Cleanup
        if: always()
        continue-on-error: true
        run: |
          kill $METRO_PID || true
          kill $TILT_SERVER_PID || true
          nix develop -c sh -c 'cd dev && tilt down' || true
          docker rm -f $(docker ps -aq) || true
          lsof -ti:10350,8080,8081 | xargs kill -9 || true

  e2e-ios:
    name: iOS
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # In case this is run on a runner without nix
      # - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      # Caching
      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            ios/Pods
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock', '**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      # Installations
      - name: Install Node Modules and Pods
        run: nix develop -c yarn install
        env:
          LANG: en_US.UTF-8

      # Metro
      - name: Start Metro
        run: |
          nix develop -c sh -c 'yarn start' &
          echo "METRO_PID=$!" >> $GITHUB_ENV

      # Start Tilt
      - name: Tilt CI
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_wait_seconds: 45
          command: nix develop -c sh -c 'cd dev && tilt ci'
      - name: Tilt Server
        run: |
          lsof -ti:10350 | xargs kill -9 || true
          nix develop -c sh -c 'cd dev && tilt up' &
          echo "TILT_SERVER_PID=$!" >> $GITHUB_ENV

      # Builds
      - run: nix develop -c yarn e2e:build ios.sim.debug

      - name: Record Simulator in Background
        run: |
          DEVICE_ID=$(xcrun simctl list devices | grep "iPhone SE (3rd generation)" | cut -d' ' -f9 | tr -d '()')
          open -a Simulator --args -CurrentDeviceUDID $DEVICE_ID
          while ! xcrun simctl list devices | grep "(Booted)"; do
            sleep 1
            echo "Waiting for Simulator device to come online..."
          done
          xcrun simctl io booted recordVideo screenRecord.mov &
          echo "SIM_RECORD=$!" >> $GITHUB_ENV

      # Tests on iOS Simulator
      - name: Run Detox Tests on iOS Simulator
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_wait_seconds: 1
          max_attempts: 3
          command: |
            rm -rf ios-recordings || true
            nix develop -c tilt trigger dev-setup
            nix develop -c tilt wait --timeout 5m --for=condition=Ready uiresources dev-setup
            nix develop -c yarn e2e:test ios.sim.debug -d -R 5 --take-screenshots all --record-videos all --record-logs all --artifacts-location ios-recordings

      - name: Stop Recording
        if: always()
        continue-on-error: true
        run: |
          kill -SIGINT $SIM_RECORD
          ffmpeg -i screenRecord.mov screenRecord.mp4

      - run: killall Simulator
        if: always()
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-recordings
          path: ios-recordings

      # Upload recording to GCS bucket
      - uses: "google-github-actions/auth@v2"
        if: always()
        with:
          credentials_json: "${{ secrets.BUILD_ARTIFACTS_BUCKET_KEY }}"
      - uses: "google-github-actions/upload-cloud-storage@v2"
        if: always()
        with:
          path: screenRecord.mp4
          gzip: false
          predefinedAcl: publicRead
          headers: |-
            content-type: video/mp4
          destination: galoy-mobile-recordings/ios-recordings/${{ github.run_id }}
      - name: Append Direct Links to GitHub Actions Summary
        if: always()
        run: |
          echo "## iOS Recording" > $GITHUB_STEP_SUMMARY

          COMPLETE_RECORDING_URL="https://storage.googleapis.com/galoy-mobile-recordings/ios-recordings/${{ github.run_id }}/screenRecord.mp4"
          echo "Full Recording: [Click here](<$COMPLETE_RECORDING_URL>)" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Test Suite:" >> $GITHUB_STEP_SUMMARY

          find ios-recordings -type f -name "*.mp4" | while read file; do
            RELATIVE_PATH="${file#ios-recordings/}"
            FILE_URL="${BASE_URL}/${RELATIVE_PATH}"
            TEST_NAME=$(echo "$RELATIVE_PATH" | sed -E 's|.*/(.*)/test\.mp4|\1|')

            echo "- $TEST_NAME" >> $GITHUB_STEP_SUMMARY
          done

      # Cleanup
      - name: Cleanup
        if: always()
        continue-on-error: true
        run: |
          kill $METRO_PID || true
          kill $TILT_SERVER_PID || true
          nix develop -c sh -c 'cd dev && tilt down' || true
          docker rm -f $(docker ps -aq) || true
          lsof -ti:10350,8080,8081 | xargs kill -9 || true
